version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  server:
    build:
      context: ./server-side
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/budget_management

  client:
    build:
      context: ./client-side
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - server

volumes:
  mongodb_data: